### PR TITLE
better variable names provided by code generators

### LINKED ISSUE #50: Imrove auto-generated names of variables in generated scripts
I could not find a command to Rename an image.
Can I just use the Rename command in ImageJ? 
But then I guess this not be recorded in the script, or would it?

### PR DESCRIPTION
**Pull request by haesleinhuepf**
Hi @tischi,

here comes a suggestion for better image variable names. Instead of "image3" it now generates a name such as "result_threshold_otsu_3". You can try it out by installing 
[clijx-assistant_-0.4.2.25-tischi.jar.zip](https://github.com/clij/assistant/files/6228747/clijx-assistant_-0.4.2.25-tischi.jar.zip)

closes #50 

Let me know what you think! If you like, I can also make you collaborator and you can change the code section I just edited for this PR.

Thanks!

Cheers,
Robert

### CODE REVIEW

**Comment by tischi** [comment]
This looks like it will be a great improvement. 
Realistically I can only look at this again in about two weeks because I want to take one week off for 🐰 🥚 😃

**Comment by haesleinhuepf** [comment]
Frohe Ostern!

**Comment by haesleinhuepf** [comment]
Hey @tischi ,

if you could try this and let me know what you think, that would be great :-)

Thanks!
Robert

**Comment by tischi** [comment]
Tried it, it is much better.
Maybe you could omit `result_` because it is there always, thus not very informative.

**Comment by haesleinhuepf** [comment]
but then commands and images have very similar names. Is it not confusing?

**Comment by tischi** [comment]
I think `Ext.CLIJ2_thresholdOtsu` is sufficiently different from `threshold_otsu`.

You could put `im_` in front to emphasize that it is an image.

**Comment by haesleinhuepf** [comment]
Ok, I will put "image_" :-)

**Pull request merged**
